package com.miicard.consumers.service.v1.claims.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * 
 * JAX-WS RI 2.2.6-1b01 
 * 
 * Generated source version: 2.2
 * 
 */
@SuppressWarnings("restriction")
@WebService(name = "IClaims", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class,
    com.miicard.consumers.service.v1.claims.transactional.impl.ObjectFactory.class
})
public interface IClaims {
	
	/**
     * @return returns com.miicard.consumers.service.v1.claims.MiiApiResponseOfMiiUserProfile
     */
    @WebMethod(operationName = "GetClaims", action = "http://tempuri.org/IClaims/GetClaims")
    @WebResult(name = "GetClaimsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetClaims", targetNamespace = "http://tempuri.org/", className = "com.miicard.consumers.service.v1.claims.GetClaims")
    @ResponseWrapper(localName = "GetClaimsResponse", targetNamespace = "http://tempuri.org/", className = "com.miicard.consumers.service.v1.claims.GetClaimsResponse")
    MiiApiResponseOfMiiUserProfile getClaims();

    /**
     * @param type
     * @return returns byte[]
     */
    @WebMethod(operationName = "AssuranceImage", action = "http://tempuri.org/IClaims/AssuranceImage")
    @WebResult(name = "AssuranceImageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AssuranceImage", targetNamespace = "http://tempuri.org/", className = "com.miicard.consumers.service.v1.claims.AssuranceImage")
    @ResponseWrapper(localName = "AssuranceImageResponse", targetNamespace = "http://tempuri.org/", className = "com.miicard.consumers.service.v1.claims.AssuranceImageResponse")
    byte[] assuranceImage(
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        String type);
    
    /**
     * @param type
     * @return returns byte[]
     */
    @WebMethod(operationName = "GetCardImage", action = "http://tempuri.org/IClaims/GetCardImage")
    @WebResult(name = "GetCardImageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCardImage", targetNamespace = "http://tempuri.org/", className = "com.miicard.consumers.service.v1.claims.GetCardImage")
    @ResponseWrapper(localName = "GetCardImageResponse", targetNamespace = "http://tempuri.org/", className = "com.miicard.consumers.service.v1.claims.GetCardImageResponse")
    byte[] getCardImage(
        @WebParam(name = "configuration", targetNamespace = "http://tempuri.org/")
        CardImageConfiguration configuration);    
    
    @WebMethod(operationName = "GetIdentitySnapshotDetails", action = "http://tempuri.org/IClaims/GetIdentitySnapshotDetails")
    @WebResult(name = "GetIdentitySnapshotDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetIdentitySnapshotDetails", targetNamespace = "http://tempuri.org/", className = "com.miicard.consumers.service.v1.claims.GetIdentitySnapshotDetails")
    @ResponseWrapper(localName = "GetIdentitySnapshotDetailsResponse", targetNamespace = "http://tempuri.org/", className = "com.miicard.consumers.service.v1.claims.GetIdentitySnapshotDetailsResponse")
    MiiApiResponseOfArrayOfIdentitySnapshotDetails getIdentitySnapshotDetails(
        @WebParam(name = "snapshotId", targetNamespace = "http://tempuri.org/")
        String snapshotId);
    
    @WebMethod(operationName = "GetIdentitySnapshot", action = "http://tempuri.org/IClaims/GetIdentitySnapshot")
    @WebResult(name = "GetIdentitySnapshotResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetIdentitySnapshot", targetNamespace = "http://tempuri.org/", className = "com.miicard.consumers.service.v1.claims.GetIdentitySnapshot")
    @ResponseWrapper(localName = "GetIdentitySnapshotResponse", targetNamespace = "http://tempuri.org/", className = "com.miicard.consumers.service.v1.claims.GetIdentitySnapshotResponse")
    MiiApiResponseOfIdentitySnapshot getIdentitySnapshot(
        @WebParam(name = "snapshotId", targetNamespace = "http://tempuri.org/")
        String snapshotId);
    
    @WebMethod(operationName = "GetIdentitySnapshotPdf", action = "http://tempuri.org/IClaims/GetIdentitySnapshotPdf")
    @WebResult(name = "GetIdentitySnapshotPdfResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetIdentitySnapshotPdf", targetNamespace = "http://tempuri.org/", className = "com.miicard.consumers.service.v1.claims.GetIdentitySnapshotPdf")
    @ResponseWrapper(localName = "GetIdentitySnapshotPdfResponse", targetNamespace = "http://tempuri.org/", className = "com.miicard.consumers.service.v1.claims.GetIdentitySnapshotPdfResponse")
    byte[] getIdentitySnapshotPdf(
        @WebParam(name = "snapshotId", targetNamespace = "http://tempuri.org/")
        String snapshotId);

    /**
     * @param socialAccountId
     * @param socialAccountType
     * @return returns com.miicard.consumers.service.v1.claims.MiiApiResponseOfboolean
     */
    @WebMethod(operationName = "IsSocialAccountAssured", action = "http://tempuri.org/IClaims/IsSocialAccountAssured")
    @WebResult(name = "IsSocialAccountAssuredResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IsSocialAccountAssured", targetNamespace = "http://tempuri.org/", className = "com.miicard.consumers.service.v1.claims.IsSocialAccountAssured")
    @ResponseWrapper(localName = "IsSocialAccountAssuredResponse", targetNamespace = "http://tempuri.org/", className = "com.miicard.consumers.service.v1.claims.IsSocialAccountAssuredResponse")
    MiiApiResponseOfBoolean isSocialAccountAssured(
        @WebParam(name = "socialAccountId", targetNamespace = "http://tempuri.org/")
        String socialAccountId,
        @WebParam(name = "socialAccountType", targetNamespace = "http://tempuri.org/")
        String socialAccountType);

    /**
     * @return returns com.miicard.consumers.service.v1.claims.MiiApiResponseOfboolean
     */
    @WebMethod(operationName = "IsUserAssured", action = "http://tempuri.org/IClaims/IsUserAssured")
    @WebResult(name = "IsUserAssuredResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IsUserAssured", targetNamespace = "http://tempuri.org/", className = "com.miicard.consumers.service.v1.claims.IsUserAssured")
    @ResponseWrapper(localName = "IsUserAssuredResponse", targetNamespace = "http://tempuri.org/", className = "com.miicard.consumers.service.v1.claims.IsUserAssuredResponse")
    MiiApiResponseOfBoolean isUserAssured();
    
    @WebMethod(operationName = "GetAuthenticationDetails", action = "http://tempuri.org/IClaims/GetAuthenticationDetails")
    @WebResult(name = "GetAuthenticationDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAuthenticationDetails", targetNamespace = "http://tempuri.org/", className = "com.miicard.consumers.service.v1.claims.GetAuthenticationDetails")
    @ResponseWrapper(localName = "GetAuthenticationDetailsResponse", targetNamespace = "http://tempuri.org/", className = "com.miicard.consumers.service.v1.claims.GetAuthenticationDetailsResponse")
    MiiApiResponseOfAuthenticationDetails getAuthenticationDetails(
		@WebParam(name = "snapshotId", targetNamespace = "http://tempuri.org/")
		String snapshotId);

    /**
     * @return returns com.miicard.consumers.service.v1.claims.MiiApiResponseOfBoolean
     */
    @WebMethod(operationName = "IsCreditBureauRefreshInProgress", action = "http://tempuri.org/IClaims/IsCreditBureauRefreshInProgress")
    @WebResult(name = "IsCreditBureauRefreshInProgressResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IsCreditBureauRefreshInProgress", targetNamespace = "http://tempuri.org/", className = "com.miicard.consumers.service.v1.claims.IsCreditBureauRefreshInProgress")
    @ResponseWrapper(localName = "IsCreditBureauRefreshInProgressResponse", targetNamespace = "http://tempuri.org/", className = "com.miicard.consumers.service.v1.claims.IsCreditBureauRefreshInProgressResponse")
    MiiApiResponseOfBoolean isCreditBureauRefreshInProgress();

    /**
     * @return returns com.miicard.consumers.service.v1.claims.MiiApiResponseOfCreditBureauRefreshStatus
     */
    @WebMethod(operationName = "RefreshCreditBureauData", action = "http://tempuri.org/IClaims/RefreshCreditBureauData")
    @WebResult(name = "RefreshCreditBureauDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RefreshCreditBureauData", targetNamespace = "http://tempuri.org/", className = "com.miicard.consumers.service.v1.claims.RefreshCreditBureauData")
    @ResponseWrapper(localName = "RefreshCreditBureauDataResponse", targetNamespace = "http://tempuri.org/", className = "com.miicard.consumers.service.v1.claims.RefreshCreditBureauDataResponse")
    MiiApiResponseOfCreditBureauRefreshStatus refreshCreditBureauData();
}
